// ==========================================
// CITADEL BUILDINGS DEFINITIONS
// ==========================================
export const BUILDINGS = {
  keep: {
    id: 'keep',
    name: 'Royal Keep',
    inkSymbol: '🏰',
    tag: 'Citadel Heart',
    description: 'Heart of the realm. Fortifies overall defense power and unlocks higher structural tiers.',
    gx: 2, gy: 2,
    baseCost: { gold: 120, wood: 100, stone: 100 },
    costMult: 1.6,
    baseHp: 650,
    type: 'core'
  },
  granary: {
    id: 'granary',
    name: 'Windmill & Granary',
    inkSymbol: '🌾',
    tag: 'Ration Silo',
    description: 'Cultivates grain crops and stores bread flour. Sustains realm population and standing garrison.',
    gx: 1, gy: 1,
    baseCost: { gold: 50, wood: 60, stone: 20 },
    costMult: 1.45,
    cycleDuration: 12,
    baseYield: { food: 55 },
    baseCapacity: 1200,
    baseHp: 280,
    type: 'eco'
  },
  well: {
    id: 'well',
    name: 'Spring Aqueduct',
    inkSymbol: '💧',
    tag: 'Aquifer',
    description: 'Pumps fresh spring aquifer water essential to ward off severe dehydration and mutinous unrest.',
    gx: 3, gy: 1,
    baseCost: { gold: 45, wood: 40, stone: 40 },
    costMult: 1.42,
    cycleDuration: 10,
    baseYield: { water: 50 },
    baseCapacity: 1200,
    baseHp: 260,
    type: 'eco'
  },
  lumber: {
    id: 'lumber',
    name: 'Timber Mill',
    inkSymbol: '🪵',
    tag: 'Forester',
    description: 'Harvests sturdy timber used for siege engines, scaffolding, and perimeter palisades.',
    gx: 0, gy: 2,
    baseCost: { gold: 40, wood: 20, stone: 50 },
    costMult: 1.4,
    cycleDuration: 15,
    baseYield: { wood: 60 },
    baseCapacity: 1500,
    baseHp: 250,
    type: 'resource'
  },
  quarry: {
    id: 'quarry',
    name: 'Granite Quarry',
    inkSymbol: '🪨',
    tag: 'Masonry',
    description: 'Chisels granite blocks to reinforce battlements and withstand enemy catapult bombardments.',
    gx: 4, gy: 2,
    baseCost: { gold: 60, wood: 50, stone: 30 },
    costMult: 1.45,
    cycleDuration: 18,
    baseYield: { stone: 60 },
    baseCapacity: 1500,
    baseHp: 320,
    type: 'resource'
  },
  greenhouse: {
    id: 'greenhouse',
    name: 'Mystic Herbalist',
    inkSymbol: '🌿',
    tag: 'Alchemist',
    description: 'Nurtures moonlit flora used for alchemical healing salves, magical wards, and raid enhancements.',
    gx: 1, gy: 3,
    baseCost: { gold: 75, wood: 60, stone: 40 },
    costMult: 1.5,
    cycleDuration: 14,
    baseYield: { flora: 35 },
    baseCapacity: 800,
    baseHp: 220,
    type: 'magic'
  },
  vault: {
    id: 'vault',
    name: 'Ironclad Vault',
    inkSymbol: '🪙',
    tag: 'Treasury',
    description: 'Mints golden crowns and keeps bullion safe beneath stone slabs during asynchronous pillage incursions.',
    gx: 3, gy: 3,
    baseCost: { gold: 100, wood: 80, stone: 110 },
    costMult: 1.55,
    cycleDuration: 20,
    baseYield: { gold: 65 },
    baseCapacity: 2000,
    baseHp: 420,
    type: 'finance'
  },
  watchtower: {
    id: 'watchtower',
    name: 'Ballista Watchtower',
    inkSymbol: '🏹',
    tag: 'Perimeter Bastion',
    description: 'Manned bastion that automatically unleashes ballista bolts at invading warbands.',
    gx: 2, gy: 0,
    baseCost: { gold: 90, wood: 75, stone: 85 },
    costMult: 1.5,
    defense: 38,
    baseHp: 460,
    type: 'military'
  }
};
